- name: SetPrompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: Install Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: Install MYSQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL File
  ansible.builtin.shell: mysql -h MYSQL-{{ env }}.vishnureddy.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - master-data

#The password hardcoded we will replace.
- name: Restart Shipping
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted



