- name: SetPrompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Server
  ansible.builtin.system_service:
    name: mysql
    state: restarted
    enabled: yes

- name: Setup MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

# password should not be hardcoded. we will change this.
