- name: set prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}


- name: Load NodeJS
  ansible.builtin.include_roles:
    name: common
    task_from: nodejs

- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: installed

- name: Load Master Data
  ansible.builtin.shell: mongosh --host mongodb-{{ env }}.vishnureddy.online </app/db/master-data.js

- name: Restart catalogue Service
  ansible.builtin.systemd_service:
    name: catalogue
    state: restarted

