#  maven_setup(){
#
#    print_heading "Install Maven"
#    dnf install maven -y &>>log_file
#    status_check $?
#
#    app_prerequisites
#    print_heading "Download Application Dependencies"
#    mvn clean package &>>log_file
#    mv target/$app_name-1.0.jar $app_name.jar &>>log_file
#    status_check $?
#


- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed


- name: Load App Prerequisites
  ansible.builtin.include_tasks:
    file: app_prerequisites.yml

- name: Install Maven Dependencies
  ansible.builtin.shell:  mvn clean package ; mv target/{{ app_name }}-1.0.jar {{ app_name }}.jar
  args:
    chdir: /app

- name: systemD setup
  ansible.builtin.tasks:
    file: system_setup.yml